version: '3.8'

services:
  db:
    image: postgres:17
    container_name: tad_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT:-5433}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
